name: Close PR
on:
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '.github/**'
      - 'README.md'
      - '.gitignore'      
  workflow_dispatch:  

jobs:
  close-pr:
    permissions: { pull-requests: write }
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v7
      id: get_issue_number
      with:
        script: |
          if (context.issue.number) {
            // Return issue number if present
            return context.issue.number;
          } else {
          // Otherwise return issue number from commit
            return (
              await github.rest.repos.listPullRequestsAssociatedWithCommit({
                commit_sha: context.sha,
                owner: context.repo.owner,
                repo: context.repo.repo,
              })
            ).data[0].number;
          }
        result-encoding: string
    - name: Close PR
      run: gh -R "${GITHUB_REPOSITORY}" pr close --comment "$( curl -fqL https://raw.githubusercontent.com/$GITHUB_REPOSITORY/main/.github/PULL_REQUEST_TEMPLATE.md || echo Repo is read-only, see README.md for details )" '${{steps.get_issue_number.outputs.result}}'
      env:
        GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

          
